# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error403.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_error3(object):
    def setupUi(self, error3):
        error3.setObjectName("error3")
        error3.resize(283, 96)
        error3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(error3)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 30, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Arabic UI Bk")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 87 10pt \"Noto Sans Arabic UI Bk\";")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 71, 71))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label_3.setObjectName("label_3")
        error3.setCentralWidget(self.centralwidget)

        self.retranslateUi(error3)
        QtCore.QMetaObject.connectSlotsByName(error3)

    def retranslateUi(self, error3):
        _translate = QtCore.QCoreApplication.translate
        error3.setWindowTitle(_translate("error3", "MainWindow"))
        self.label_4.setText(_translate("error3", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans Arabic UI Bk\'; font-size:10pt; font-weight:88; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:11pt; font-weight:400; color:#000000;\">Tenemos Problemas Con La </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:11pt; font-weight:400; color:#000000;\">Base De Datos.</span></p></body></html>"))
        self.label_3.setText(_translate("error3", "<html><head/><body><p><img src=\":/recurso/img/resolver.png\"/></p></body></html>"))
import recurso_rc
