# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error402.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_error2(object):
    def setupUi(self, error2):
        error2.setObjectName("error2")
        error2.resize(280, 96)
        error2.setMinimumSize(QtCore.QSize(280, 96))
        error2.setMaximumSize(QtCore.QSize(280, 96))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/recurso/img/pregunta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        error2.setWindowIcon(icon)
        error2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(error2)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 71, 61))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 30, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Arabic UI Bk")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 87 10pt \"Noto Sans Arabic UI Bk\";")
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.label_3.raise_()
        error2.setCentralWidget(self.centralwidget)

        self.retranslateUi(error2)
        QtCore.QMetaObject.connectSlotsByName(error2)

    def retranslateUi(self, error2):
        _translate = QtCore.QCoreApplication.translate
        error2.setWindowTitle(_translate("error2", "Error 402"))
        self.label_3.setText(_translate("error2", "<html><head/><body><p><img src=\":/recurso/img/pregunta.png\"/></p></body></html>"))
        self.label_5.setText(_translate("error2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans Arabic UI Bk\'; font-size:10pt; font-weight:88; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:11pt; font-weight:400; color:#000000;\">No Encontramos La Información </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:11pt; font-weight:400; color:#000000;\">En Nuestra base De Datos</span></p></body></html>"))
import recurso_rc
