# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_game1(object):
    def setupUi(self, game1):
        game1.setObjectName("game1")
        game1.resize(522, 518)
        game1.setMinimumSize(QtCore.QSize(522, 510))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/recurso/img/02button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        game1.setWindowIcon(icon)
        game1.setAutoFillBackground(False)
        game1.setStyleSheet("alternate-background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(90, 0, 182, 255), stop:0.289216 rgba(150, 155, 255, 255), stop:0.921569 rgba(74, 206, 205, 255));")
        self.centralwidget = QtWidgets.QWidget(game1)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(90, 0, 182, 255), stop:0.289216 rgba(150, 155, 255, 255), stop:0.921569 rgba(74, 206, 205, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.barGame = QtWidgets.QTabWidget(self.centralwidget)
        self.barGame.setGeometry(QtCore.QRect(0, 0, 521, 519))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.barGame.setFont(font)
        self.barGame.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.barGame.setAcceptDrops(False)
        self.barGame.setStyleSheet("alternate-background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(90, 0, 182, 255), stop:0.289216 rgba(150, 155, 255, 255), stop:0.921569 rgba(74, 206, 205, 255));\n"
"color: rgb(255, 255, 255)")
        self.barGame.setTabPosition(QtWidgets.QTabWidget.North)
        self.barGame.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.barGame.setElideMode(QtCore.Qt.ElideNone)
        self.barGame.setTabBarAutoHide(False)
        self.barGame.setObjectName("barGame")
        self.create = QtWidgets.QWidget()
        self.create.setObjectName("create")
        self.bcrear = QtWidgets.QPushButton(self.create)
        self.bcrear.setGeometry(QtCore.QRect(280, 330, 61, 61))
        self.bcrear.setStyleSheet("image: url(:/recurso/img/elegir.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.bcrear.setText("")
        self.bcrear.setAutoDefault(True)
        self.bcrear.setObjectName("bcrear")
        self.jnombre = QtWidgets.QLineEdit(self.create)
        self.jnombre.setGeometry(QtCore.QRect(190, 130, 241, 31))
        self.jnombre.setAutoFillBackground(False)
        self.jnombre.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.jnombre.setText("")
        self.jnombre.setPlaceholderText("")
        self.jnombre.setObjectName("jnombre")
        self.nombre = QtWidgets.QLabel(self.create)
        self.nombre.setGeometry(QtCore.QRect(100, 130, 71, 31))
        self.nombre.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.nombre.setObjectName("nombre")
        self.clasificacion = QtWidgets.QLabel(self.create)
        self.clasificacion.setGeometry(QtCore.QRect(70, 180, 101, 31))
        self.clasificacion.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.clasificacion.setObjectName("clasificacion")
        self.jclasif = QtWidgets.QLineEdit(self.create)
        self.jclasif.setGeometry(QtCore.QRect(190, 180, 241, 31))
        self.jclasif.setAutoFillBackground(False)
        self.jclasif.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.jclasif.setText("")
        self.jclasif.setObjectName("jclasif")
        self.descripcion = QtWidgets.QLabel(self.create)
        self.descripcion.setGeometry(QtCore.QRect(80, 230, 91, 31))
        self.descripcion.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);\n"
"")
        self.descripcion.setObjectName("descripcion")
        self.jdesc = QtWidgets.QLineEdit(self.create)
        self.jdesc.setGeometry(QtCore.QRect(190, 230, 241, 31))
        self.jdesc.setAutoFillBackground(False)
        self.jdesc.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.jdesc.setText("")
        self.jdesc.setObjectName("jdesc")
        self.jgene = QtWidgets.QLineEdit(self.create)
        self.jgene.setGeometry(QtCore.QRect(190, 280, 241, 31))
        self.jgene.setAutoFillBackground(False)
        self.jgene.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.jgene.setText("")
        self.jgene.setObjectName("jgene")
        self.label = QtWidgets.QLabel(self.create)
        self.label.setGeometry(QtCore.QRect(60, 20, 381, 51))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"")
        self.label.setObjectName("label")
        self.indicaciones = QtWidgets.QLabel(self.create)
        self.indicaciones.setEnabled(True)
        self.indicaciones.setGeometry(QtCore.QRect(140, 80, 221, 31))
        self.indicaciones.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.indicaciones.setObjectName("indicaciones")
        self.genero = QtWidgets.QLabel(self.create)
        self.genero.setGeometry(QtCore.QRect(110, 280, 61, 31))
        self.genero.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.genero.setObjectName("genero")
        self.atras = QtWidgets.QPushButton(self.create)
        self.atras.setGeometry(QtCore.QRect(180, 330, 61, 61))
        self.atras.setStyleSheet("image: url(:/recurso/img/atras.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.atras.setText("")
        self.atras.setAutoDefault(True)
        self.atras.setObjectName("atras")
        self.progressBar = QtWidgets.QProgressBar(self.create)
        self.progressBar.setGeometry(QtCore.QRect(100, 400, 371, 23))
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.cargando = QtWidgets.QLabel(self.create)
        self.cargando.setGeometry(QtCore.QRect(190, 420, 141, 20))
        self.cargando.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.cargando.setObjectName("cargando")
        self.barGame.addTab(self.create, "")
        self.google = QtWidgets.QWidget()
        self.google.setObjectName("google")
        self.tableWidget = QtWidgets.QTableWidget(self.google)
        self.tableWidget.setGeometry(QtCore.QRect(50, 210, 421, 261))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("color:#000000;\n"
"background-color: rgb(255, 255, 255);\n"
"border :none;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.labelCod = QtWidgets.QLabel(self.google)
        self.labelCod.setGeometry(QtCore.QRect(20, 100, 141, 31))
        self.labelCod.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.labelCod.setObjectName("labelCod")
        self.lcod = QtWidgets.QLineEdit(self.google)
        self.lcod.setGeometry(QtCore.QRect(170, 100, 241, 31))
        self.lcod.setAutoFillBackground(False)
        self.lcod.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.lcod.setText("")
        self.lcod.setObjectName("lcod")
        self.bCode = QtWidgets.QPushButton(self.google)
        self.bCode.setGeometry(QtCore.QRect(420, 90, 61, 51))
        self.bCode.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"image: url(:/recurso/img/busqueda.png);")
        self.bCode.setText("")
        self.bCode.setAutoDefault(True)
        self.bCode.setObjectName("bCode")
        self.label_2 = QtWidgets.QLabel(self.google)
        self.label_2.setGeometry(QtCore.QRect(-50, 30, 571, 481))
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.google)
        self.label_3.setGeometry(QtCore.QRect(50, 20, 381, 51))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"")
        self.label_3.setObjectName("label_3")
        self.atras_2 = QtWidgets.QPushButton(self.google)
        self.atras_2.setGeometry(QtCore.QRect(20, 10, 31, 41))
        self.atras_2.setStyleSheet("image: url(:/recurso/img/atras.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.atras_2.setText("")
        self.atras_2.setAutoDefault(True)
        self.atras_2.setObjectName("atras_2")
        self.limpiar = QtWidgets.QPushButton(self.google)
        self.limpiar.setGeometry(QtCore.QRect(400, 410, 71, 51))
        self.limpiar.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"image: url(:/recurso/img/limpiar.png)")
        self.limpiar.setText("")
        self.limpiar.setAutoDefault(True)
        self.limpiar.setObjectName("limpiar")
        self.label_2.raise_()
        self.tableWidget.raise_()
        self.labelCod.raise_()
        self.lcod.raise_()
        self.bCode.raise_()
        self.label_3.raise_()
        self.atras_2.raise_()
        self.limpiar.raise_()
        self.barGame.addTab(self.google, "")
        self.refresh = QtWidgets.QWidget()
        self.refresh.setObjectName("refresh")
        self.label_4 = QtWidgets.QLabel(self.refresh)
        self.label_4.setGeometry(QtCore.QRect(50, 20, 381, 51))
        self.label_4.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"")
        self.label_4.setObjectName("label_4")
        self.lcod_2 = QtWidgets.QLineEdit(self.refresh)
        self.lcod_2.setGeometry(QtCore.QRect(190, 90, 241, 31))
        self.lcod_2.setAutoFillBackground(False)
        self.lcod_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.lcod_2.setText("")
        self.lcod_2.setObjectName("lcod_2")
        self.labelCod_3 = QtWidgets.QLabel(self.refresh)
        self.labelCod_3.setEnabled(True)
        self.labelCod_3.setGeometry(QtCore.QRect(40, 90, 141, 31))
        self.labelCod_3.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.labelCod_3.setObjectName("labelCod_3")
        self.labelCod_4 = QtWidgets.QLabel(self.refresh)
        self.labelCod_4.setEnabled(True)
        self.labelCod_4.setGeometry(QtCore.QRect(90, 130, 301, 31))
        self.labelCod_4.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.labelCod_4.setObjectName("labelCod_4")
        self.nombre_2 = QtWidgets.QLabel(self.refresh)
        self.nombre_2.setGeometry(QtCore.QRect(110, 170, 71, 31))
        self.nombre_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.nombre_2.setObjectName("nombre_2")
        self.jclasif_2 = QtWidgets.QLineEdit(self.refresh)
        self.jclasif_2.setGeometry(QtCore.QRect(200, 220, 241, 31))
        self.jclasif_2.setAutoFillBackground(False)
        self.jclasif_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.jclasif_2.setText("")
        self.jclasif_2.setObjectName("jclasif_2")
        self.clasificacion_2 = QtWidgets.QLabel(self.refresh)
        self.clasificacion_2.setGeometry(QtCore.QRect(80, 220, 101, 31))
        self.clasificacion_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.clasificacion_2.setObjectName("clasificacion_2")
        self.jgene_2 = QtWidgets.QLineEdit(self.refresh)
        self.jgene_2.setGeometry(QtCore.QRect(200, 320, 241, 31))
        self.jgene_2.setAutoFillBackground(False)
        self.jgene_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.jgene_2.setText("")
        self.jgene_2.setObjectName("jgene_2")
        self.jnombre_2 = QtWidgets.QLineEdit(self.refresh)
        self.jnombre_2.setGeometry(QtCore.QRect(200, 170, 241, 31))
        self.jnombre_2.setAutoFillBackground(False)
        self.jnombre_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.jnombre_2.setText("")
        self.jnombre_2.setObjectName("jnombre_2")
        self.descripcion_2 = QtWidgets.QLabel(self.refresh)
        self.descripcion_2.setGeometry(QtCore.QRect(90, 270, 91, 31))
        self.descripcion_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.descripcion_2.setObjectName("descripcion_2")
        self.jdesc_2 = QtWidgets.QLineEdit(self.refresh)
        self.jdesc_2.setGeometry(QtCore.QRect(200, 270, 241, 31))
        self.jdesc_2.setAutoFillBackground(False)
        self.jdesc_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.jdesc_2.setText("")
        self.jdesc_2.setObjectName("jdesc_2")
        self.genero_2 = QtWidgets.QLabel(self.refresh)
        self.genero_2.setGeometry(QtCore.QRect(120, 320, 61, 31))
        self.genero_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.genero_2.setObjectName("genero_2")
        self.bactualizar = QtWidgets.QPushButton(self.refresh)
        self.bactualizar.setGeometry(QtCore.QRect(430, 80, 61, 51))
        self.bactualizar.setStyleSheet("image: url(:/recurso/img/elegir.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.bactualizar.setText("")
        self.bactualizar.setAutoDefault(True)
        self.bactualizar.setObjectName("bactualizar")
        self.atras_3 = QtWidgets.QPushButton(self.refresh)
        self.atras_3.setGeometry(QtCore.QRect(20, 20, 31, 41))
        self.atras_3.setStyleSheet("image: url(:/recurso/img/atras.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.atras_3.setText("")
        self.atras_3.setAutoDefault(True)
        self.atras_3.setObjectName("atras_3")
        self.progressBar_2 = QtWidgets.QProgressBar(self.refresh)
        self.progressBar_2.setGeometry(QtCore.QRect(80, 420, 371, 23))
        self.progressBar_2.setAutoFillBackground(False)
        self.progressBar_2.setStyleSheet("")
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setInvertedAppearance(False)
        self.progressBar_2.setObjectName("progressBar_2")
        self.cargando_2 = QtWidgets.QLabel(self.refresh)
        self.cargando_2.setGeometry(QtCore.QRect(180, 440, 141, 20))
        self.cargando_2.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.cargando_2.setObjectName("cargando_2")
        self.bactualizar2 = QtWidgets.QPushButton(self.refresh)
        self.bactualizar2.setGeometry(QtCore.QRect(220, 360, 61, 61))
        self.bactualizar2.setStyleSheet("image:url(:/recurso/img/actualizar.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.bactualizar2.setText("")
        self.bactualizar2.setAutoDefault(True)
        self.bactualizar2.setObjectName("bactualizar2")
        self.barGame.addTab(self.refresh, "")
        self.delete_2 = QtWidgets.QWidget()
        self.delete_2.setObjectName("delete_2")
        self.label_5 = QtWidgets.QLabel(self.delete_2)
        self.label_5.setGeometry(QtCore.QRect(50, 20, 381, 51))
        self.label_5.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"")
        self.label_5.setObjectName("label_5")
        self.atras_4 = QtWidgets.QPushButton(self.delete_2)
        self.atras_4.setGeometry(QtCore.QRect(20, 20, 31, 41))
        self.atras_4.setStyleSheet("image: url(:/recurso/img/atras.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.atras_4.setText("")
        self.atras_4.setAutoDefault(True)
        self.atras_4.setObjectName("atras_4")
        self.labelCod_7 = QtWidgets.QLabel(self.delete_2)
        self.labelCod_7.setGeometry(QtCore.QRect(40, 120, 141, 31))
        self.labelCod_7.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.labelCod_7.setObjectName("labelCod_7")
        self.lcod_0 = QtWidgets.QLineEdit(self.delete_2)
        self.lcod_0.setGeometry(QtCore.QRect(190, 120, 241, 31))
        self.lcod_0.setAutoFillBackground(False)
        self.lcod_0.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.lcod_0.setText("")
        self.lcod_0.setObjectName("lcod_0")
        self.checkBox = QtWidgets.QCheckBox(self.delete_2)
        self.checkBox.setGeometry(QtCore.QRect(40, 210, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Arabic Blk")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(11)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("font: 87 10pt \"Noto Sans Arabic Blk\";\n"
"background-color: rgba(0, 0, 0,0%);\n"
"color:rgb(170, 0, 0)")
        self.checkBox.setObjectName("checkBox")
        self.labelCod_8 = QtWidgets.QLabel(self.delete_2)
        self.labelCod_8.setGeometry(QtCore.QRect(60, 230, 421, 101))
        self.labelCod_8.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.labelCod_8.setObjectName("labelCod_8")
        self.bborrar = QtWidgets.QPushButton(self.delete_2)
        self.bborrar.setGeometry(QtCore.QRect(380, 370, 61, 61))
        self.bborrar.setStyleSheet("image: url(:/recurso/img/elegir.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.bborrar.setText("")
        self.bborrar.setAutoDefault(True)
        self.bborrar.setObjectName("bborrar")
        self.progressBar_0 = QtWidgets.QProgressBar(self.delete_2)
        self.progressBar_0.setGeometry(QtCore.QRect(50, 390, 331, 23))
        self.progressBar_0.setAutoFillBackground(False)
        self.progressBar_0.setStyleSheet("")
        self.progressBar_0.setProperty("value", 0)
        self.progressBar_0.setInvertedAppearance(False)
        self.progressBar_0.setObjectName("progressBar_0")
        self.cargando_0 = QtWidgets.QLabel(self.delete_2)
        self.cargando_0.setGeometry(QtCore.QRect(140, 410, 141, 20))
        self.cargando_0.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.cargando_0.setObjectName("cargando_0")
        self.barGame.addTab(self.delete_2, "")
        game1.setCentralWidget(self.centralwidget)

        self.retranslateUi(game1)
        self.barGame.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(game1)
        game1.setTabOrder(self.jnombre, self.jclasif)
        game1.setTabOrder(self.jclasif, self.jdesc)
        game1.setTabOrder(self.jdesc, self.jgene)
        game1.setTabOrder(self.jgene, self.atras)
        game1.setTabOrder(self.atras, self.bcrear)
        game1.setTabOrder(self.bcrear, self.barGame)
        game1.setTabOrder(self.barGame, self.atras_2)
        game1.setTabOrder(self.atras_2, self.lcod)
        game1.setTabOrder(self.lcod, self.bCode)
        game1.setTabOrder(self.bCode, self.tableWidget)
        game1.setTabOrder(self.tableWidget, self.limpiar)
        game1.setTabOrder(self.limpiar, self.lcod_2)
        game1.setTabOrder(self.lcod_2, self.jclasif_2)
        game1.setTabOrder(self.jclasif_2, self.jgene_2)
        game1.setTabOrder(self.jgene_2, self.jnombre_2)
        game1.setTabOrder(self.jnombre_2, self.jdesc_2)
        game1.setTabOrder(self.jdesc_2, self.bactualizar)
        game1.setTabOrder(self.bactualizar, self.atras_3)
        game1.setTabOrder(self.atras_3, self.atras_4)
        game1.setTabOrder(self.atras_4, self.lcod_0)
        game1.setTabOrder(self.lcod_0, self.checkBox)
        game1.setTabOrder(self.checkBox, self.bborrar)

    def retranslateUi(self, game1):
        _translate = QtCore.QCoreApplication.translate
        game1.setWindowTitle(_translate("game1", "Juego"))
        self.jnombre.setToolTip(_translate("game1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej:Minecraft</span></p></body></html>"))
        self.nombre.setText(_translate("game1", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Nombre:</span></p></body></html>"))
        self.clasificacion.setText(_translate("game1", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Clasificación:</span></p></body></html>"))
        self.jclasif.setToolTip(_translate("game1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej: Early Childhood(EC)</span></p></body></html>"))
        self.descripcion.setText(_translate("game1", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Descripción: </span></p></body></html>"))
        self.jdesc.setToolTip(_translate("game1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej: juego de Bloques.</span></p></body></html>"))
        self.jgene.setToolTip(_translate("game1", "<html><head/><body><p><span style=\" color:#474747;\">Ej: Sandbox</span></p></body></html>"))
        self.label.setText(_translate("game1", "<html><head/><body><p align=\"center\"><img src=\":/recurso/img/01title.png\"/></p></body></html>"))
        self.indicaciones.setText(_translate("game1", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Ingrese Los Datos Del Juego. </span></p></body></html>"))
        self.genero.setText(_translate("game1", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Género:</span></p></body></html>"))
        self.cargando.setText(_translate("game1", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.barGame.setTabText(self.barGame.indexOf(self.create), _translate("game1", "Crear"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("game1", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("game1", "Clasificación"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("game1", "Descripción"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("game1", "Género"))
        self.labelCod.setText(_translate("game1", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Nombre del Juego:  </span></p></body></html>"))
        self.lcod.setToolTip(_translate("game1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#747474;\">Ej:Minecraft</span></p></body></html>"))
        self.label_2.setText(_translate("game1", "<html><head/><body><p><img src=\":/recurso/img/cuadro1.png\"/></p></body></html>"))
        self.label_3.setText(_translate("game1", "<html><head/><body><p align=\"center\"><img src=\":/recurso/img/01title.png\"/></p></body></html>"))
        self.barGame.setTabText(self.barGame.indexOf(self.google), _translate("game1", "Buscar"))
        self.label_4.setText(_translate("game1", "<html><head/><body><p align=\"center\"><img src=\":/recurso/img/01title.png\"/></p></body></html>"))
        self.lcod_2.setToolTip(_translate("game1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#747474;\">Ej:Minecraft</span></p></body></html>"))
        self.labelCod_3.setText(_translate("game1", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Nombre del Juego: </span></p></body></html>"))
        self.labelCod_4.setText(_translate("game1", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600; color:#ffffff;\">Ingrese los datos que desea modificar:</span></p></body></html>"))
        self.nombre_2.setText(_translate("game1", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Nombre:</span></p></body></html>"))
        self.jclasif_2.setToolTip(_translate("game1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej: Early Childhood(EC)</span></p></body></html>"))
        self.clasificacion_2.setText(_translate("game1", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Clasificación:</span></p></body></html>"))
        self.jgene_2.setToolTip(_translate("game1", "<html><head/><body><p><span style=\" color:#474747;\">Ej: Sandbox</span></p></body></html>"))
        self.jnombre_2.setToolTip(_translate("game1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej:Minecraft</span></p></body></html>"))
        self.descripcion_2.setText(_translate("game1", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Descripción: </span></p></body></html>"))
        self.jdesc_2.setToolTip(_translate("game1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej: juego de Bloques.</span></p></body></html>"))
        self.genero_2.setText(_translate("game1", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Género:</span></p></body></html>"))
        self.cargando_2.setText(_translate("game1", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.barGame.setTabText(self.barGame.indexOf(self.refresh), _translate("game1", "Actualizar"))
        self.label_5.setText(_translate("game1", "<html><head/><body><p align=\"center\"><img src=\":/recurso/img/01title.png\"/></p></body></html>"))
        self.labelCod_7.setText(_translate("game1", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Nombre del Juego: </span></p></body></html>"))
        self.lcod_0.setToolTip(_translate("game1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#747474;\">Ej:Minecraft</span></p></body></html>"))
        self.checkBox.setText(_translate("game1", "ADVERTENCIA:"))
        self.labelCod_8.setText(_translate("game1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aa0000;\">En cuanto usted elimine el elemento nombrado, éste dejara de </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aa0000;\">existir y no habrá forma de recuperarlo, si usted está seguro </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aa0000;\">de esto continue.</span></p></body></html>"))
        self.cargando_0.setText(_translate("game1", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.barGame.setTabText(self.barGame.indexOf(self.delete_2), _translate("game1", "Borrar"))
import recurso_rc
