# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(434, 520)
        MainWindow.setMinimumSize(QtCore.QSize(434, 520))
        MainWindow.setMaximumSize(QtCore.QSize(434, 520))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/recurso/img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setAcceptDrops(False)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.122549 rgba(109, 117, 255, 255), stop:0.921569 rgba(74, 206, 205, 255));\n"
"border-radius: 20px;\n"
"border: 1px solid #00007f;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setMidLineWidth(-1)
        self.frame.setObjectName("frame")
        self.bjuego = QtWidgets.QPushButton(self.frame)
        self.bjuego.setGeometry(QtCore.QRect(40, 120, 81, 71))
        self.bjuego.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.bjuego.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"image: url(:/recurso/img/02button.png);\n"
"border:none;\n"
"")
        self.bjuego.setText("")
        self.bjuego.setAutoDefault(True)
        self.bjuego.setDefault(False)
        self.bjuego.setObjectName("bjuego")
        self.ljuego = QtWidgets.QLabel(self.frame)
        self.ljuego.setEnabled(True)
        self.ljuego.setGeometry(QtCore.QRect(50, 190, 61, 21))
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.ljuego.setFont(font)
        self.ljuego.setMouseTracking(True)
        self.ljuego.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border :none;")
        self.ljuego.setObjectName("ljuego")
        self.bplatform = QtWidgets.QPushButton(self.frame)
        self.bplatform.setGeometry(QtCore.QRect(180, 120, 71, 61))
        self.bplatform.setStyleSheet("image: url(:/recurso/img/03plataform.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.bplatform.setText("")
        self.bplatform.setAutoDefault(True)
        self.bplatform.setObjectName("bplatform")
        self.lplatform = QtWidgets.QLabel(self.frame)
        self.lplatform.setEnabled(True)
        self.lplatform.setGeometry(QtCore.QRect(150, 190, 121, 21))
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lplatform.setFont(font)
        self.lplatform.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.lplatform.setObjectName("lplatform")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 40, 431, 61))
        self.label.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.label.setObjectName("label")
        self.bexit = QtWidgets.QPushButton(self.frame)
        self.bexit.setGeometry(QtCore.QRect(170, 440, 81, 71))
        self.bexit.setMouseTracking(False)
        self.bexit.setTabletTracking(True)
        self.bexit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.bexit.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"image: url(:/recurso/img/05exit.png);\n"
"border:none;\n"
"")
        self.bexit.setText("")
        self.bexit.setCheckable(False)
        self.bexit.setAutoDefault(True)
        self.bexit.setDefault(False)
        self.bexit.setFlat(False)
        self.bexit.setObjectName("bexit")
        self.ljuego_2 = QtWidgets.QLabel(self.frame)
        self.ljuego_2.setEnabled(True)
        self.ljuego_2.setGeometry(QtCore.QRect(50, 300, 91, 21))
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.ljuego_2.setFont(font)
        self.ljuego_2.setMouseTracking(True)
        self.ljuego_2.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border :none;")
        self.ljuego_2.setObjectName("ljuego_2")
        self.busuario = QtWidgets.QPushButton(self.frame)
        self.busuario.setGeometry(QtCore.QRect(50, 230, 91, 71))
        self.busuario.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.busuario.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"image: url(:/recurso/img/usuario.png);\n"
"border:none;\n"
"")
        self.busuario.setText("")
        self.busuario.setAutoDefault(True)
        self.busuario.setDefault(False)
        self.busuario.setObjectName("busuario")
        self.btarjeta = QtWidgets.QPushButton(self.frame)
        self.btarjeta.setGeometry(QtCore.QRect(280, 230, 91, 71))
        self.btarjeta.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btarjeta.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"image: url(:/recurso/img/tarjeta.png);\n"
"border:none;\n"
"")
        self.btarjeta.setText("")
        self.btarjeta.setAutoDefault(True)
        self.btarjeta.setDefault(False)
        self.btarjeta.setObjectName("btarjeta")
        self.ljuego_3 = QtWidgets.QLabel(self.frame)
        self.ljuego_3.setEnabled(True)
        self.ljuego_3.setGeometry(QtCore.QRect(280, 300, 91, 21))
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.ljuego_3.setFont(font)
        self.ljuego_3.setMouseTracking(True)
        self.ljuego_3.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border :none;")
        self.ljuego_3.setObjectName("ljuego_3")
        self.bversion = QtWidgets.QPushButton(self.frame)
        self.bversion.setGeometry(QtCore.QRect(300, 120, 91, 71))
        self.bversion.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.bversion.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"image: url(:/recurso/img/04version.png);\n"
"border:none;\n"
"")
        self.bversion.setText("")
        self.bversion.setAutoDefault(True)
        self.bversion.setDefault(False)
        self.bversion.setObjectName("bversion")
        self.ljuego_7 = QtWidgets.QLabel(self.frame)
        self.ljuego_7.setEnabled(True)
        self.ljuego_7.setGeometry(QtCore.QRect(300, 190, 91, 21))
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.ljuego_7.setFont(font)
        self.ljuego_7.setMouseTracking(True)
        self.ljuego_7.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border :none;")
        self.ljuego_7.setObjectName("ljuego_7")
        self.ljuego_4 = QtWidgets.QLabel(self.frame)
        self.ljuego_4.setEnabled(True)
        self.ljuego_4.setGeometry(QtCore.QRect(170, 370, 91, 21))
        font = QtGui.QFont()
        font.setFamily("xos4 Terminus")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.ljuego_4.setFont(font)
        self.ljuego_4.setMouseTracking(True)
        self.ljuego_4.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border :none;")
        self.ljuego_4.setObjectName("ljuego_4")
        self.binforme = QtWidgets.QPushButton(self.frame)
        self.binforme.setGeometry(QtCore.QRect(170, 300, 91, 71))
        self.binforme.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.binforme.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"image:url(:/recurso/img/reporte.png);\n"
"border:none;\n"
"")
        self.binforme.setText("")
        self.binforme.setAutoDefault(True)
        self.binforme.setDefault(False)
        self.binforme.setObjectName("binforme")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.bexit.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menú"))
        self.ljuego.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">JUEGO</span></p></body></html>"))
        self.lplatform.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">PLATAFORMA</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/recurso/img/01title.png\"/></p></body></html>"))
        self.ljuego_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">USUARIO</span></p></body></html>"))
        self.ljuego_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">TARJETA</span></p></body></html>"))
        self.ljuego_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">VERSIÓN</span></p></body></html>"))
        self.ljuego_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">INFORME</span></p></body></html>"))
import recurso_rc
