# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plataforma.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plataforma(object):
    def setupUi(self, plataforma):
        plataforma.setObjectName("plataforma")
        plataforma.resize(521, 519)
        plataforma.setMinimumSize(QtCore.QSize(521, 519))
        plataforma.setMaximumSize(QtCore.QSize(521, 519))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/recurso/img/03plataform.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        plataforma.setWindowIcon(icon)
        plataforma.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(90, 0, 182, 255), stop:0.289216 rgba(150, 155, 255, 255), stop:0.921569 rgba(74, 206, 205, 255));")
        self.centralwidget = QtWidgets.QWidget(plataforma)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 521, 521))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("color:rgb(255, 255, 255)")
        self.tabWidget.setObjectName("tabWidget")
        self.crear = QtWidgets.QWidget()
        self.crear.setObjectName("crear")
        self.logo_1 = QtWidgets.QLabel(self.crear)
        self.logo_1.setGeometry(QtCore.QRect(60, 20, 381, 51))
        self.logo_1.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"")
        self.logo_1.setObjectName("logo_1")
        self.indicaciones = QtWidgets.QLabel(self.crear)
        self.indicaciones.setEnabled(True)
        self.indicaciones.setGeometry(QtCore.QRect(120, 100, 271, 31))
        self.indicaciones.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.indicaciones.setObjectName("indicaciones")
        self.nom = QtWidgets.QLabel(self.crear)
        self.nom.setGeometry(QtCore.QRect(90, 170, 71, 31))
        self.nom.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.nom.setObjectName("nom")
        self.model = QtWidgets.QLabel(self.crear)
        self.model.setGeometry(QtCore.QRect(90, 270, 71, 31))
        self.model.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);\n"
"")
        self.model.setObjectName("model")
        self.nombre = QtWidgets.QLineEdit(self.crear)
        self.nombre.setGeometry(QtCore.QRect(180, 170, 241, 31))
        self.nombre.setAutoFillBackground(False)
        self.nombre.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.nombre.setText("")
        self.nombre.setPlaceholderText("")
        self.nombre.setObjectName("nombre")
        self.modelo = QtWidgets.QLineEdit(self.crear)
        self.modelo.setGeometry(QtCore.QRect(180, 270, 241, 31))
        self.modelo.setAutoFillBackground(False)
        self.modelo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.modelo.setText("")
        self.modelo.setObjectName("modelo")
        self.fech = QtWidgets.QLabel(self.crear)
        self.fech.setGeometry(QtCore.QRect(110, 220, 51, 31))
        self.fech.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.fech.setObjectName("fech")
        self.fecha = QtWidgets.QDateEdit(self.crear)
        self.fecha.setGeometry(QtCore.QRect(180, 220, 241, 31))
        self.fecha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border: 1px solid #00007f;")
        self.fecha.setCalendarPopup(True)
        self.fecha.setObjectName("fecha")
        self.progreso1 = QtWidgets.QProgressBar(self.crear)
        self.progreso1.setGeometry(QtCore.QRect(90, 400, 371, 23))
        self.progreso1.setAutoFillBackground(False)
        self.progreso1.setStyleSheet("")
        self.progreso1.setProperty("value", 0)
        self.progreso1.setInvertedAppearance(False)
        self.progreso1.setObjectName("progreso1")
        self.aceptar = QtWidgets.QPushButton(self.crear)
        self.aceptar.setGeometry(QtCore.QRect(280, 330, 61, 61))
        self.aceptar.setStyleSheet("image: url(:/recurso/img/elegir.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.aceptar.setText("")
        self.aceptar.setAutoDefault(True)
        self.aceptar.setObjectName("aceptar")
        self.atras1 = QtWidgets.QPushButton(self.crear)
        self.atras1.setGeometry(QtCore.QRect(180, 330, 61, 61))
        self.atras1.setStyleSheet("image: url(:/recurso/img/atras.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.atras1.setText("")
        self.atras1.setAutoDefault(True)
        self.atras1.setObjectName("atras1")
        self.cargando = QtWidgets.QLabel(self.crear)
        self.cargando.setGeometry(QtCore.QRect(190, 420, 141, 20))
        self.cargando.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.cargando.setObjectName("cargando")
        self.tabWidget.addTab(self.crear, "")
        self.buscar = QtWidgets.QWidget()
        self.buscar.setObjectName("buscar")
        self.logo_2 = QtWidgets.QLabel(self.buscar)
        self.logo_2.setGeometry(QtCore.QRect(60, 20, 381, 51))
        self.logo_2.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"")
        self.logo_2.setObjectName("logo_2")
        self.resultado = QtWidgets.QTableWidget(self.buscar)
        self.resultado.setGeometry(QtCore.QRect(90, 210, 331, 261))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.resultado.setFont(font)
        self.resultado.setStyleSheet("color:#000000;\n"
"background-color: rgb(255, 255, 255);\n"
"border :none;")
        self.resultado.setObjectName("resultado")
        self.resultado.setColumnCount(3)
        self.resultado.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.resultado.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.resultado.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.resultado.setHorizontalHeaderItem(2, item)
        self.atras2 = QtWidgets.QPushButton(self.buscar)
        self.atras2.setGeometry(QtCore.QRect(20, 20, 31, 41))
        self.atras2.setStyleSheet("image: url(:/recurso/img/atras.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.atras2.setText("")
        self.atras2.setAutoDefault(True)
        self.atras2.setObjectName("atras2")
        self.frame = QtWidgets.QLabel(self.buscar)
        self.frame.setGeometry(QtCore.QRect(-50, 30, 571, 481))
        self.frame.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.frame.setObjectName("frame")
        self.codigo = QtWidgets.QLineEdit(self.buscar)
        self.codigo.setGeometry(QtCore.QRect(210, 100, 201, 31))
        self.codigo.setAutoFillBackground(False)
        self.codigo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.codigo.setText("")
        self.codigo.setObjectName("codigo")
        self.busca = QtWidgets.QPushButton(self.buscar)
        self.busca.setGeometry(QtCore.QRect(420, 90, 61, 51))
        self.busca.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"image: url(:/recurso/img/busqueda.png);")
        self.busca.setText("")
        self.busca.setAutoDefault(True)
        self.busca.setObjectName("busca")
        self.nom_2 = QtWidgets.QLabel(self.buscar)
        self.nom_2.setGeometry(QtCore.QRect(10, 100, 201, 31))
        self.nom_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.nom_2.setObjectName("nom_2")
        self.limpiar = QtWidgets.QPushButton(self.buscar)
        self.limpiar.setGeometry(QtCore.QRect(410, 410, 71, 51))
        self.limpiar.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"image: url(:/recurso/img/limpiar.png)")
        self.limpiar.setText("")
        self.limpiar.setAutoDefault(True)
        self.limpiar.setObjectName("limpiar")
        self.frame.raise_()
        self.logo_2.raise_()
        self.resultado.raise_()
        self.atras2.raise_()
        self.codigo.raise_()
        self.busca.raise_()
        self.nom_2.raise_()
        self.limpiar.raise_()
        self.tabWidget.addTab(self.buscar, "")
        self.actualizar = QtWidgets.QWidget()
        self.actualizar.setObjectName("actualizar")
        self.logo_3 = QtWidgets.QLabel(self.actualizar)
        self.logo_3.setGeometry(QtCore.QRect(60, 20, 381, 51))
        self.logo_3.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"")
        self.logo_3.setObjectName("logo_3")
        self.codigo_2 = QtWidgets.QLineEdit(self.actualizar)
        self.codigo_2.setGeometry(QtCore.QRect(260, 90, 201, 31))
        self.codigo_2.setAutoFillBackground(False)
        self.codigo_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.codigo_2.setText("")
        self.codigo_2.setObjectName("codigo_2")
        self.nom_5 = QtWidgets.QLabel(self.actualizar)
        self.nom_5.setGeometry(QtCore.QRect(60, 90, 201, 31))
        self.nom_5.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.nom_5.setObjectName("nom_5")
        self.fech_3 = QtWidgets.QLabel(self.actualizar)
        self.fech_3.setGeometry(QtCore.QRect(120, 250, 51, 31))
        self.fech_3.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.fech_3.setObjectName("fech_3")
        self.modelo_3 = QtWidgets.QLineEdit(self.actualizar)
        self.modelo_3.setGeometry(QtCore.QRect(190, 300, 241, 31))
        self.modelo_3.setAutoFillBackground(False)
        self.modelo_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.modelo_3.setText("")
        self.modelo_3.setObjectName("modelo_3")
        self.nom_6 = QtWidgets.QLabel(self.actualizar)
        self.nom_6.setGeometry(QtCore.QRect(100, 200, 71, 31))
        self.nom_6.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.nom_6.setObjectName("nom_6")
        self.nombre_3 = QtWidgets.QLineEdit(self.actualizar)
        self.nombre_3.setGeometry(QtCore.QRect(190, 200, 241, 31))
        self.nombre_3.setAutoFillBackground(False)
        self.nombre_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.nombre_3.setText("")
        self.nombre_3.setPlaceholderText("")
        self.nombre_3.setObjectName("nombre_3")
        self.model_3 = QtWidgets.QLabel(self.actualizar)
        self.model_3.setGeometry(QtCore.QRect(100, 300, 71, 31))
        self.model_3.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);\n"
"")
        self.model_3.setObjectName("model_3")
        self.fecha_3 = QtWidgets.QDateEdit(self.actualizar)
        self.fecha_3.setGeometry(QtCore.QRect(190, 250, 241, 31))
        self.fecha_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border: 1px solid #00007f;")
        self.fecha_3.setCalendarPopup(True)
        self.fecha_3.setDate(QtCore.QDate(1900, 1, 1))
        self.fecha_3.setObjectName("fecha_3")
        self.progreso2 = QtWidgets.QProgressBar(self.actualizar)
        self.progreso2.setGeometry(QtCore.QRect(80, 410, 371, 23))
        self.progreso2.setAutoFillBackground(False)
        self.progreso2.setStyleSheet("")
        self.progreso2.setProperty("value", 0)
        self.progreso2.setInvertedAppearance(False)
        self.progreso2.setObjectName("progreso2")
        self.aceptar_3 = QtWidgets.QPushButton(self.actualizar)
        self.aceptar_3.setGeometry(QtCore.QRect(210, 340, 61, 61))
        self.aceptar_3.setStyleSheet("image: url(:/recurso/img/elegir.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.aceptar_3.setText("")
        self.aceptar_3.setAutoDefault(True)
        self.aceptar_3.setObjectName("aceptar_3")
        self.atras3 = QtWidgets.QPushButton(self.actualizar)
        self.atras3.setGeometry(QtCore.QRect(30, 20, 31, 41))
        self.atras3.setStyleSheet("image: url(:/recurso/img/atras.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.atras3.setText("")
        self.atras3.setAutoDefault(True)
        self.atras3.setObjectName("atras3")
        self.cargando2 = QtWidgets.QLabel(self.actualizar)
        self.cargando2.setGeometry(QtCore.QRect(180, 430, 141, 20))
        self.cargando2.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.cargando2.setObjectName("cargando2")
        self.indicaciones_2 = QtWidgets.QLabel(self.actualizar)
        self.indicaciones_2.setEnabled(True)
        self.indicaciones_2.setGeometry(QtCore.QRect(120, 150, 271, 31))
        self.indicaciones_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.indicaciones_2.setObjectName("indicaciones_2")
        self.tabWidget.addTab(self.actualizar, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.logo_4 = QtWidgets.QLabel(self.tab_4)
        self.logo_4.setGeometry(QtCore.QRect(60, 20, 381, 51))
        self.logo_4.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"")
        self.logo_4.setObjectName("logo_4")
        self.aceptar_4 = QtWidgets.QPushButton(self.tab_4)
        self.aceptar_4.setGeometry(QtCore.QRect(390, 380, 61, 61))
        self.aceptar_4.setStyleSheet("image: url(:/recurso/img/elegir.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.aceptar_4.setText("")
        self.aceptar_4.setAutoDefault(True)
        self.aceptar_4.setObjectName("aceptar_4")
        self.codigo_3 = QtWidgets.QLineEdit(self.tab_4)
        self.codigo_3.setGeometry(QtCore.QRect(230, 130, 241, 31))
        self.codigo_3.setAutoFillBackground(False)
        self.codigo_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.codigo_3.setText("")
        self.codigo_3.setObjectName("codigo_3")
        self.textnom = QtWidgets.QLabel(self.tab_4)
        self.textnom.setGeometry(QtCore.QRect(30, 130, 201, 31))
        self.textnom.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.textnom.setObjectName("textnom")
        self.progreso3 = QtWidgets.QProgressBar(self.tab_4)
        self.progreso3.setGeometry(QtCore.QRect(60, 400, 331, 23))
        self.progreso3.setAutoFillBackground(False)
        self.progreso3.setStyleSheet("")
        self.progreso3.setProperty("value", 0)
        self.progreso3.setInvertedAppearance(False)
        self.progreso3.setObjectName("progreso3")
        self.texto = QtWidgets.QLabel(self.tab_4)
        self.texto.setGeometry(QtCore.QRect(70, 240, 421, 101))
        self.texto.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.texto.setObjectName("texto")
        self.atras4 = QtWidgets.QPushButton(self.tab_4)
        self.atras4.setGeometry(QtCore.QRect(20, 20, 31, 41))
        self.atras4.setStyleSheet("image: url(:/recurso/img/atras.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.atras4.setText("")
        self.atras4.setAutoDefault(True)
        self.atras4.setObjectName("atras4")
        self.cargando3 = QtWidgets.QLabel(self.tab_4)
        self.cargando3.setGeometry(QtCore.QRect(130, 420, 141, 20))
        self.cargando3.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.cargando3.setObjectName("cargando3")
        self.checkBox = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox.setGeometry(QtCore.QRect(40, 220, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Arabic Blk")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(11)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("font: 87 10pt \"Noto Sans Arabic Blk\";\n"
"background-color: rgba(0, 0, 0,0%);\n"
"color:rgb(170, 0, 0)")
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.tabWidget.addTab(self.tab_4, "")
        plataforma.setCentralWidget(self.centralwidget)

        self.retranslateUi(plataforma)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(plataforma)
        plataforma.setTabOrder(self.nombre, self.fecha)
        plataforma.setTabOrder(self.fecha, self.modelo)
        plataforma.setTabOrder(self.modelo, self.atras1)
        plataforma.setTabOrder(self.atras1, self.aceptar)
        plataforma.setTabOrder(self.aceptar, self.tabWidget)
        plataforma.setTabOrder(self.tabWidget, self.atras2)
        plataforma.setTabOrder(self.atras2, self.codigo)
        plataforma.setTabOrder(self.codigo, self.busca)
        plataforma.setTabOrder(self.busca, self.atras3)
        plataforma.setTabOrder(self.atras3, self.codigo_2)
        plataforma.setTabOrder(self.codigo_2, self.nombre_3)
        plataforma.setTabOrder(self.nombre_3, self.fecha_3)
        plataforma.setTabOrder(self.fecha_3, self.modelo_3)
        plataforma.setTabOrder(self.modelo_3, self.aceptar_3)
        plataforma.setTabOrder(self.aceptar_3, self.atras4)
        plataforma.setTabOrder(self.atras4, self.codigo_3)
        plataforma.setTabOrder(self.codigo_3, self.checkBox)
        plataforma.setTabOrder(self.checkBox, self.aceptar_4)
        plataforma.setTabOrder(self.aceptar_4, self.limpiar)
        plataforma.setTabOrder(self.limpiar, self.resultado)

    def retranslateUi(self, plataforma):
        _translate = QtCore.QCoreApplication.translate
        plataforma.setWindowTitle(_translate("plataforma", "Plataforma"))
        self.logo_1.setText(_translate("plataforma", "<html><head/><body><p align=\"center\"><img src=\":/recurso/img/01title.png\"/></p></body></html>"))
        self.indicaciones.setText(_translate("plataforma", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Ingrese Los Datos De La Plataforma. </span></p></body></html>"))
        self.nom.setText(_translate("plataforma", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Nombre:</span></p></body></html>"))
        self.model.setText(_translate("plataforma", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Modelo: </span></p></body></html>"))
        self.nombre.setToolTip(_translate("plataforma", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej:Nintendo Switch</span></p></body></html>"))
        self.modelo.setToolTip(_translate("plataforma", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej: Switch.</span></p></body></html>"))
        self.fech.setText(_translate("plataforma", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Fecha:</span></p></body></html>"))
        self.fecha.setToolTip(_translate("plataforma", "<html><head/><body><p><span style=\" color:#474747;\">Ej:02/09/2017</span></p></body></html>"))
        self.fecha.setWhatsThis(_translate("plataforma", "<html><head/><body><p><br/></p></body></html>"))
        self.fecha.setDisplayFormat(_translate("plataforma", "dd/MM/yyyy"))
        self.cargando.setText(_translate("plataforma", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.crear), _translate("plataforma", "Crear"))
        self.logo_2.setText(_translate("plataforma", "<html><head/><body><p align=\"center\"><img src=\":/recurso/img/01title.png\"/></p></body></html>"))
        item = self.resultado.horizontalHeaderItem(0)
        item.setText(_translate("plataforma", "Nombre"))
        item = self.resultado.horizontalHeaderItem(1)
        item.setText(_translate("plataforma", "Fecha"))
        item = self.resultado.horizontalHeaderItem(2)
        item.setText(_translate("plataforma", "Modelo"))
        self.frame.setText(_translate("plataforma", "<html><head/><body><p><img src=\":/recurso/img/cuadro1.png\"/></p></body></html>"))
        self.codigo.setToolTip(_translate("plataforma", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#747474;\">Ej:Nintendo </span></p></body></html>"))
        self.nom_2.setText(_translate("plataforma", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Nombre de la plataforma: </span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.buscar), _translate("plataforma", "Buscar"))
        self.logo_3.setText(_translate("plataforma", "<html><head/><body><p align=\"center\"><img src=\":/recurso/img/01title.png\"/></p></body></html>"))
        self.codigo_2.setToolTip(_translate("plataforma", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#747474;\">Ej:Nintendo</span></p></body></html>"))
        self.nom_5.setText(_translate("plataforma", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Nombre de la plataforma: </span></p></body></html>"))
        self.fech_3.setText(_translate("plataforma", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Fecha:</span></p></body></html>"))
        self.modelo_3.setToolTip(_translate("plataforma", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej: Switch</span></p></body></html>"))
        self.nom_6.setText(_translate("plataforma", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Nombre:</span></p></body></html>"))
        self.nombre_3.setToolTip(_translate("plataforma", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej:Nintendo Switch</span></p></body></html>"))
        self.model_3.setText(_translate("plataforma", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Modelo: </span></p></body></html>"))
        self.fecha_3.setToolTip(_translate("plataforma", "<html><head/><body><p><span style=\" color:#474747;\">Ej:02/09/2017</span></p></body></html>"))
        self.fecha_3.setDisplayFormat(_translate("plataforma", "dd/MM/yyyy"))
        self.cargando2.setText(_translate("plataforma", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.indicaciones_2.setText(_translate("plataforma", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Ingrese Los Datos De La Plataforma. </span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.actualizar), _translate("plataforma", "Actualizar"))
        self.logo_4.setText(_translate("plataforma", "<html><head/><body><p align=\"center\"><img src=\":/recurso/img/01title.png\"/></p></body></html>"))
        self.codigo_3.setToolTip(_translate("plataforma", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#747474;\">Ej:Nintendo</span></p></body></html>"))
        self.textnom.setText(_translate("plataforma", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Nombre De La Plataforma: </span></p></body></html>"))
        self.texto.setText(_translate("plataforma", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aa0000;\">En cuanto usted elimine el elemento nombrado, éste dejara de </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aa0000;\">existir y no habrá forma de recuperarlo, si usted está seguro </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aa0000;\">de esto continue.</span></p></body></html>"))
        self.cargando3.setText(_translate("plataforma", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.checkBox.setText(_translate("plataforma", "ADVERTENCIA:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("plataforma", "Borrar"))
import recurso_rc
