# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tarjeta.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tarjeta(object):
    def setupUi(self, tarjeta):
        tarjeta.setObjectName("tarjeta")
        tarjeta.resize(523, 518)
        tarjeta.setMinimumSize(QtCore.QSize(523, 518))
        tarjeta.setMaximumSize(QtCore.QSize(523, 518))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/recurso/img/tarjeta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tarjeta.setWindowIcon(icon)
        tarjeta.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(90, 0, 182, 255), stop:0.289216 rgba(150, 155, 255, 255), stop:0.921569 rgba(74, 206, 205, 255));")
        self.centralwidget = QtWidgets.QWidget(tarjeta)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 521, 521))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("color:rgb(255, 255, 255)")
        self.tabWidget.setObjectName("tabWidget")
        self.crear = QtWidgets.QWidget()
        self.crear.setObjectName("crear")
        self.logo_1 = QtWidgets.QLabel(self.crear)
        self.logo_1.setGeometry(QtCore.QRect(60, 20, 381, 51))
        self.logo_1.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"")
        self.logo_1.setObjectName("logo_1")
        self.nom = QtWidgets.QLabel(self.crear)
        self.nom.setGeometry(QtCore.QRect(90, 240, 71, 31))
        self.nom.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.nom.setObjectName("nom")
        self.model = QtWidgets.QLabel(self.crear)
        self.model.setGeometry(QtCore.QRect(70, 180, 91, 31))
        self.model.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);\n"
"")
        self.model.setObjectName("model")
        self.textclave1 = QtWidgets.QLineEdit(self.crear)
        self.textclave1.setGeometry(QtCore.QRect(180, 240, 241, 31))
        self.textclave1.setAutoFillBackground(False)
        self.textclave1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.textclave1.setText("")
        self.textclave1.setPlaceholderText("")
        self.textclave1.setObjectName("textclave1")
        self.textbanco1 = QtWidgets.QLineEdit(self.crear)
        self.textbanco1.setGeometry(QtCore.QRect(180, 180, 241, 31))
        self.textbanco1.setAutoFillBackground(False)
        self.textbanco1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.textbanco1.setText("")
        self.textbanco1.setObjectName("textbanco1")
        self.fech = QtWidgets.QLabel(self.crear)
        self.fech.setGeometry(QtCore.QRect(60, 300, 101, 31))
        self.fech.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.fech.setObjectName("fech")
        self.textfecha1 = QtWidgets.QDateEdit(self.crear)
        self.textfecha1.setGeometry(QtCore.QRect(180, 300, 241, 31))
        self.textfecha1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"border: 1px solid #00007f;")
        self.textfecha1.setCalendarPopup(True)
        self.textfecha1.setObjectName("textfecha1")
        self.progreso1 = QtWidgets.QProgressBar(self.crear)
        self.progreso1.setGeometry(QtCore.QRect(90, 430, 371, 23))
        self.progreso1.setAutoFillBackground(False)
        self.progreso1.setStyleSheet("")
        self.progreso1.setProperty("value", 0)
        self.progreso1.setInvertedAppearance(False)
        self.progreso1.setObjectName("progreso1")
        self.aceptar1 = QtWidgets.QPushButton(self.crear)
        self.aceptar1.setGeometry(QtCore.QRect(280, 360, 61, 61))
        self.aceptar1.setStyleSheet("image: url(:/recurso/img/elegir.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.aceptar1.setText("")
        self.aceptar1.setAutoDefault(True)
        self.aceptar1.setObjectName("aceptar1")
        self.atras1 = QtWidgets.QPushButton(self.crear)
        self.atras1.setGeometry(QtCore.QRect(180, 360, 61, 61))
        self.atras1.setStyleSheet("image: url(:/recurso/img/atras.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.atras1.setText("")
        self.atras1.setAutoDefault(True)
        self.atras1.setObjectName("atras1")
        self.cargando1 = QtWidgets.QLabel(self.crear)
        self.cargando1.setGeometry(QtCore.QRect(190, 450, 141, 20))
        self.cargando1.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.cargando1.setObjectName("cargando1")
        self.indicaciones_2 = QtWidgets.QLabel(self.crear)
        self.indicaciones_2.setEnabled(True)
        self.indicaciones_2.setGeometry(QtCore.QRect(0, 80, 511, 31))
        self.indicaciones_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.indicaciones_2.setObjectName("indicaciones_2")
        self.combousuario = QtWidgets.QComboBox(self.crear)
        self.combousuario.setGeometry(QtCore.QRect(180, 120, 241, 32))
        self.combousuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:rgb(0,0,0)")
        self.combousuario.setEditable(True)
        self.combousuario.setObjectName("combousuario")
        self.combousuario.addItem("")
        self.combousuario.setItemText(0, "")
        self.nom_3 = QtWidgets.QLabel(self.crear)
        self.nom_3.setGeometry(QtCore.QRect(100, 120, 61, 31))
        self.nom_3.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.nom_3.setObjectName("nom_3")
        self.tabWidget.addTab(self.crear, "")
        self.buscar = QtWidgets.QWidget()
        self.buscar.setObjectName("buscar")
        self.logo_2 = QtWidgets.QLabel(self.buscar)
        self.logo_2.setGeometry(QtCore.QRect(60, 20, 381, 51))
        self.logo_2.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"")
        self.logo_2.setObjectName("logo_2")
        self.resultado = QtWidgets.QTableWidget(self.buscar)
        self.resultado.setGeometry(QtCore.QRect(50, 210, 411, 261))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.resultado.setFont(font)
        self.resultado.setStyleSheet("color:#000000;\n"
"background-color: rgb(255, 255, 255);\n"
"border :none;")
        self.resultado.setObjectName("resultado")
        self.resultado.setColumnCount(4)
        self.resultado.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.resultado.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.resultado.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.resultado.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.resultado.setHorizontalHeaderItem(3, item)
        self.atras2 = QtWidgets.QPushButton(self.buscar)
        self.atras2.setGeometry(QtCore.QRect(20, 20, 31, 41))
        self.atras2.setStyleSheet("image: url(:/recurso/img/atras.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.atras2.setText("")
        self.atras2.setAutoDefault(True)
        self.atras2.setObjectName("atras2")
        self.frame = QtWidgets.QLabel(self.buscar)
        self.frame.setGeometry(QtCore.QRect(-50, 30, 571, 481))
        self.frame.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.frame.setObjectName("frame")
        self.codigo1 = QtWidgets.QLineEdit(self.buscar)
        self.codigo1.setGeometry(QtCore.QRect(210, 100, 201, 31))
        self.codigo1.setAutoFillBackground(False)
        self.codigo1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.codigo1.setText("")
        self.codigo1.setObjectName("codigo1")
        self.busca = QtWidgets.QPushButton(self.buscar)
        self.busca.setGeometry(QtCore.QRect(420, 90, 61, 51))
        self.busca.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"image: url(:/recurso/img/busqueda.png);")
        self.busca.setText("")
        self.busca.setAutoDefault(True)
        self.busca.setObjectName("busca")
        self.nom_2 = QtWidgets.QLabel(self.buscar)
        self.nom_2.setGeometry(QtCore.QRect(40, 100, 171, 31))
        self.nom_2.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.nom_2.setObjectName("nom_2")
        self.limpiar = QtWidgets.QPushButton(self.buscar)
        self.limpiar.setGeometry(QtCore.QRect(410, 410, 71, 51))
        self.limpiar.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"image: url(:/recurso/img/limpiar.png)")
        self.limpiar.setText("")
        self.limpiar.setAutoDefault(True)
        self.limpiar.setObjectName("limpiar")
        self.nom_4 = QtWidgets.QLabel(self.buscar)
        self.nom_4.setGeometry(QtCore.QRect(220, 160, 71, 31))
        self.nom_4.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.nom_4.setObjectName("nom_4")
        self.frame.raise_()
        self.logo_2.raise_()
        self.resultado.raise_()
        self.atras2.raise_()
        self.codigo1.raise_()
        self.busca.raise_()
        self.nom_2.raise_()
        self.limpiar.raise_()
        self.nom_4.raise_()
        self.tabWidget.addTab(self.buscar, "")
        self.actualizar = QtWidgets.QWidget()
        self.actualizar.setObjectName("actualizar")
        self.logo_3 = QtWidgets.QLabel(self.actualizar)
        self.logo_3.setGeometry(QtCore.QRect(60, 20, 381, 51))
        self.logo_3.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"")
        self.logo_3.setObjectName("logo_3")
        self.codigo2 = QtWidgets.QLineEdit(self.actualizar)
        self.codigo2.setGeometry(QtCore.QRect(210, 90, 201, 31))
        self.codigo2.setAutoFillBackground(False)
        self.codigo2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.codigo2.setText("")
        self.codigo2.setObjectName("codigo2")
        self.nom_5 = QtWidgets.QLabel(self.actualizar)
        self.nom_5.setGeometry(QtCore.QRect(40, 90, 171, 31))
        self.nom_5.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.nom_5.setObjectName("nom_5")
        self.nom_7 = QtWidgets.QLabel(self.actualizar)
        self.nom_7.setGeometry(QtCore.QRect(150, 130, 231, 31))
        self.nom_7.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.nom_7.setObjectName("nom_7")
        self.progreso2 = QtWidgets.QProgressBar(self.actualizar)
        self.progreso2.setGeometry(QtCore.QRect(110, 440, 371, 23))
        self.progreso2.setAutoFillBackground(False)
        self.progreso2.setStyleSheet("")
        self.progreso2.setProperty("value", 0)
        self.progreso2.setInvertedAppearance(False)
        self.progreso2.setObjectName("progreso2")
        self.atras3 = QtWidgets.QPushButton(self.actualizar)
        self.atras3.setGeometry(QtCore.QRect(30, 20, 31, 41))
        self.atras3.setStyleSheet("image: url(:/recurso/img/atras.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.atras3.setText("")
        self.atras3.setAutoDefault(True)
        self.atras3.setObjectName("atras3")
        self.cargando2 = QtWidgets.QLabel(self.actualizar)
        self.cargando2.setGeometry(QtCore.QRect(180, 450, 141, 20))
        self.cargando2.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.cargando2.setObjectName("cargando2")
        self.act = QtWidgets.QPushButton(self.actualizar)
        self.act.setGeometry(QtCore.QRect(250, 380, 61, 61))
        self.act.setStyleSheet("image:url(:/recurso/img/actualizar.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.act.setText("")
        self.act.setAutoDefault(True)
        self.act.setObjectName("act")
        self.acp = QtWidgets.QPushButton(self.actualizar)
        self.acp.setGeometry(QtCore.QRect(420, 80, 61, 61))
        self.acp.setStyleSheet("image: url(:/recurso/img/elegir.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.acp.setText("")
        self.acp.setAutoDefault(True)
        self.acp.setObjectName("acp")
        self.textclave2 = QtWidgets.QLineEdit(self.actualizar)
        self.textclave2.setGeometry(QtCore.QRect(170, 250, 241, 31))
        self.textclave2.setAutoFillBackground(False)
        self.textclave2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.textclave2.setText("")
        self.textclave2.setPlaceholderText("")
        self.textclave2.setObjectName("textclave2")
        self.model_4 = QtWidgets.QLabel(self.actualizar)
        self.model_4.setGeometry(QtCore.QRect(60, 190, 91, 31))
        self.model_4.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);\n"
"")
        self.model_4.setObjectName("model_4")
        self.textbanco2 = QtWidgets.QLineEdit(self.actualizar)
        self.textbanco2.setGeometry(QtCore.QRect(170, 190, 241, 31))
        self.textbanco2.setAutoFillBackground(False)
        self.textbanco2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.textbanco2.setText("")
        self.textbanco2.setObjectName("textbanco2")
        self.nom_15 = QtWidgets.QLabel(self.actualizar)
        self.nom_15.setGeometry(QtCore.QRect(80, 250, 71, 31))
        self.nom_15.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.nom_15.setObjectName("nom_15")
        self.fech_4 = QtWidgets.QLabel(self.actualizar)
        self.fech_4.setGeometry(QtCore.QRect(40, 310, 111, 31))
        self.fech_4.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.fech_4.setObjectName("fech_4")
        self.textfecha2 = QtWidgets.QLineEdit(self.actualizar)
        self.textfecha2.setGeometry(QtCore.QRect(170, 310, 241, 31))
        self.textfecha2.setAutoFillBackground(False)
        self.textfecha2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.textfecha2.setText("")
        self.textfecha2.setPlaceholderText("")
        self.textfecha2.setObjectName("textfecha2")
        self.act.raise_()
        self.logo_3.raise_()
        self.codigo2.raise_()
        self.nom_5.raise_()
        self.nom_7.raise_()
        self.progreso2.raise_()
        self.atras3.raise_()
        self.cargando2.raise_()
        self.acp.raise_()
        self.textclave2.raise_()
        self.model_4.raise_()
        self.textbanco2.raise_()
        self.nom_15.raise_()
        self.fech_4.raise_()
        self.textfecha2.raise_()
        self.tabWidget.addTab(self.actualizar, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.logo_4 = QtWidgets.QLabel(self.tab_4)
        self.logo_4.setGeometry(QtCore.QRect(60, 20, 381, 51))
        self.logo_4.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border:none;\n"
"")
        self.logo_4.setObjectName("logo_4")
        self.aceptar_4 = QtWidgets.QPushButton(self.tab_4)
        self.aceptar_4.setGeometry(QtCore.QRect(390, 380, 61, 61))
        self.aceptar_4.setStyleSheet("image: url(:/recurso/img/elegir.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.aceptar_4.setText("")
        self.aceptar_4.setAutoDefault(True)
        self.aceptar_4.setObjectName("aceptar_4")
        self.codigo3 = QtWidgets.QLineEdit(self.tab_4)
        self.codigo3.setGeometry(QtCore.QRect(230, 130, 241, 31))
        self.codigo3.setAutoFillBackground(False)
        self.codigo3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 1px solid #00007f;\n"
"color:#000000;")
        self.codigo3.setText("")
        self.codigo3.setObjectName("codigo3")
        self.textnom = QtWidgets.QLabel(self.tab_4)
        self.textnom.setGeometry(QtCore.QRect(30, 130, 201, 31))
        self.textnom.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.textnom.setObjectName("textnom")
        self.progreso3 = QtWidgets.QProgressBar(self.tab_4)
        self.progreso3.setGeometry(QtCore.QRect(60, 400, 331, 23))
        self.progreso3.setAutoFillBackground(False)
        self.progreso3.setStyleSheet("")
        self.progreso3.setProperty("value", 0)
        self.progreso3.setInvertedAppearance(False)
        self.progreso3.setObjectName("progreso3")
        self.texto = QtWidgets.QLabel(self.tab_4)
        self.texto.setGeometry(QtCore.QRect(70, 240, 421, 101))
        self.texto.setStyleSheet("border:none;\n"
"background-color: rgba(0, 0, 0,0%);")
        self.texto.setObjectName("texto")
        self.atras4 = QtWidgets.QPushButton(self.tab_4)
        self.atras4.setGeometry(QtCore.QRect(20, 20, 31, 41))
        self.atras4.setStyleSheet("image: url(:/recurso/img/atras.png);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:none;")
        self.atras4.setText("")
        self.atras4.setAutoDefault(True)
        self.atras4.setObjectName("atras4")
        self.cargando3 = QtWidgets.QLabel(self.tab_4)
        self.cargando3.setGeometry(QtCore.QRect(130, 420, 141, 20))
        self.cargando3.setStyleSheet("background-color: rgba(0, 0, 0,0%);")
        self.cargando3.setObjectName("cargando3")
        self.checkBox = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox.setGeometry(QtCore.QRect(50, 220, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Arabic Blk")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(11)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("font: 87 10pt \"Noto Sans Arabic Blk\";\n"
"background-color: rgba(0, 0, 0,0%);\n"
"color:rgb(170, 0, 0)")
        self.checkBox.setObjectName("checkBox")
        self.tabWidget.addTab(self.tab_4, "")
        tarjeta.setCentralWidget(self.centralwidget)

        self.retranslateUi(tarjeta)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tarjeta)

    def retranslateUi(self, tarjeta):
        _translate = QtCore.QCoreApplication.translate
        tarjeta.setWindowTitle(_translate("tarjeta", "Tarjeta"))
        self.logo_1.setText(_translate("tarjeta", "<html><head/><body><p align=\"center\"><img src=\":/recurso/img/01title.png\"/></p></body></html>"))
        self.nom.setText(_translate("tarjeta", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Clave:</span></p></body></html>"))
        self.model.setText(_translate("tarjeta", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Banco: </span></p></body></html>"))
        self.textclave1.setToolTip(_translate("tarjeta", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej:124567825789425</span></p></body></html>"))
        self.textbanco1.setToolTip(_translate("tarjeta", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej: Banamex</span></p></body></html>"))
        self.fech.setText(_translate("tarjeta", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Vencimiento:</span></p></body></html>"))
        self.textfecha1.setToolTip(_translate("tarjeta", "<html><head/><body><p><span style=\" color:#474747;\">Ej:02/09/2017</span></p></body></html>"))
        self.textfecha1.setWhatsThis(_translate("tarjeta", "<html><head/><body><p><br/></p></body></html>"))
        self.textfecha1.setDisplayFormat(_translate("tarjeta", "dd/MM/yyyy"))
        self.cargando1.setText(_translate("tarjeta", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.indicaciones_2.setText(_translate("tarjeta", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Ingrese Los Datos Del Usuario:</span></p></body></html>"))
        self.combousuario.setToolTip(_translate("tarjeta", "<html><head/><body><p><span style=\" color:#474747;\">Puede Suscar o Selecionar.</span></p></body></html>"))
        self.nom_3.setText(_translate("tarjeta", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Usuario:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.crear), _translate("tarjeta", "Crear o Añadir"))
        self.logo_2.setText(_translate("tarjeta", "<html><head/><body><p align=\"center\"><img src=\":/recurso/img/01title.png\"/></p></body></html>"))
        item = self.resultado.horizontalHeaderItem(0)
        item.setText(_translate("tarjeta", "Usuario"))
        item = self.resultado.horizontalHeaderItem(1)
        item.setText(_translate("tarjeta", "Tarjeta"))
        item = self.resultado.horizontalHeaderItem(2)
        item.setText(_translate("tarjeta", "Banco"))
        item = self.resultado.horizontalHeaderItem(3)
        item.setText(_translate("tarjeta", "Vencimiento"))
        self.frame.setText(_translate("tarjeta", "<html><head/><body><p><img src=\":/recurso/img/cuadro1.png\"/></p></body></html>"))
        self.codigo1.setToolTip(_translate("tarjeta", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#747474;\">Ej:Nintendo </span></p></body></html>"))
        self.nom_2.setText(_translate("tarjeta", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Nombre de la Usuario: </span></p></body></html>"))
        self.nom_4.setText(_translate("tarjeta", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Tarjetas: </span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.buscar), _translate("tarjeta", "Buscar"))
        self.logo_3.setText(_translate("tarjeta", "<html><head/><body><p align=\"center\"><img src=\":/recurso/img/01title.png\"/></p></body></html>"))
        self.codigo2.setToolTip(_translate("tarjeta", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#747474;\">Ej:1235848451316415</span></p></body></html>"))
        self.nom_5.setText(_translate("tarjeta", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Clave de la Tarjeta: </span></p></body></html>"))
        self.nom_7.setText(_translate("tarjeta", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Ingrese Los Datos A Modificar:</span></p></body></html>"))
        self.cargando2.setText(_translate("tarjeta", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.textclave2.setToolTip(_translate("tarjeta", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej:25156514812512512545</span></p></body></html>"))
        self.model_4.setText(_translate("tarjeta", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Banco: </span></p></body></html>"))
        self.textbanco2.setToolTip(_translate("tarjeta", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej: Banamex</span></p></body></html>"))
        self.nom_15.setText(_translate("tarjeta", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Clave:</span></p></body></html>"))
        self.fech_4.setText(_translate("tarjeta", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Vencimiento:</span></p></body></html>"))
        self.textfecha2.setToolTip(_translate("tarjeta", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#474747;\">Ej:05/05/05</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.actualizar), _translate("tarjeta", "Actualizar"))
        self.logo_4.setText(_translate("tarjeta", "<html><head/><body><p align=\"center\"><img src=\":/recurso/img/01title.png\"/></p></body></html>"))
        self.codigo3.setToolTip(_translate("tarjeta", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#747474;\">Ej:15975368426</span></p></body></html>"))
        self.textnom.setText(_translate("tarjeta", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; font-weight:600;\">Nombre De la Tarjeta: </span></p></body></html>"))
        self.texto.setText(_translate("tarjeta", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aa0000;\">En cuanto usted elimine el elemento nombrado, éste dejara de </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aa0000;\">existir y no habrá forma de recuperarlo, si usted está seguro </span></p>\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#aa0000;\">de esto continue.</span></p></body></html>"))
        self.cargando3.setText(_translate("tarjeta", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.checkBox.setText(_translate("tarjeta", "ADVERTENCIA:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("tarjeta", "Borrar"))
import recurso_rc
